default_job = "check"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy"]
need_stdout = false

[jobs.run]
command = [ "cargo", "run", "main.bp" ]
need_stdout = true
allow_warnings = true
background = true

[keybindings]
a = "job:check"
c = "job:clippy"
r = "job:run"
