[package]
name = "bp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
logos = "0.15.0"

[profile.dev.package.'*']
opt-level = 'z'
strip = true
debug = false
